services:
  api:
    build:
      context: ./firecrawl/repository/apps/api
    networks:
      - pomera-net-v1
    env_file:
      - ./firecrawl/.env
  playwright-service:
    build:
      context: ./firecrawl/repository/apps/playwright-service-ts
    networks:
      - pomera-net-v1
    env_file:
      - ./firecrawl/.env
  worker:
    build:
      context: ./firecrawl/repository/apps/api
    networks:
      - pomera-net-v1
    env_file:
      - ./firecrawl/.env
  redis:
    networks:
      - pomera-net-v1
    env_file:
      - ./firecrawl/.env

networks:
  pomera-net-v1:
    external: true
