version: '3.9'

services:
  store:
    build:
      context: ./store
    networks:
      - pomera-net-v1

  analytics:
    build:
      context: ./analytics
    depends_on:
      - store
    networks:
      - pomera-net-v1

networks:
  pomera-net-v1:
    name: pomera-net-v1