services:
  api:
    networks:
      - pomera-net-v1
  playwright-service:
    networks:
      - pomera-net-v1
  redis:
    networks:
      - pomera-net-v1

networks:
  pomera-net-v1:
    external: true
